"""Numerically stable implementation of generalized eigensolvers.

This module provides functions for computing eigenvalues and eigenvectors of
symmetric matrices and generalized eigenvalue problems, with a focus on
numerical stability during automatic differentiation (backpropagation),
particularly in the presence of (nearly) degenerate eigenvalues.

The implementation is based on the Lorentzian broadening approach described in:
Colburn, S., & Majumdar, A. Inverse design and flexible parameterization
of meta-optics using algorithmic differentiation. Communications Physics 4,
54 (2021). https://doi.org/10.1038/s42005-021-00568-6
"""


from __future__ import annotations

import jax
import jax.numpy as jnp
from jax import custom_vjp
from jaxtyping import Array, Float

# Default parameters for degeneracy tolerance and broadening
DEGENERACY_TOLERANCE = 1e-6
BROADENING = 1e-10


@custom_vjp
def stable_eigh(
    A: Float[Array, "n n"],
) -> tuple[Float[Array, "n"], Float[Array, "n n"]]:
    """Computes eigenvalues and eigenvectors of a symmetric matrix with stable gradients.

    Uses a custom vector-Jacobian product (VJP) to ensure numerically stable
    gradients, particularly in the presence of degenerate or nearly-degenerate
    eigenvalues.

    Args:
      A: A real symmetric matrix of shape (n, n).

    Returns:
      A tuple (evals, evecs) where:
        - evals: Eigenvalues in ascending order of shape (n,).
        - evecs: Matrix of shape (n, n) whose columns are the normalized
          eigenvectors corresponding to each eigenvalue.
    """
    evals, evecs = jnp.linalg.eigh(A)
    return evals, evecs


def stable_eigh_fwd(
    A: Float[Array, "n n"],
) -> tuple[
    tuple[Float[Array, "n"], Float[Array, "n n"]],
    tuple[tuple[Float[Array, "n"], Float[Array, "n n"]], Float[Array, "n n"]],
]:
    """Forward pass for symmetric eigendecomposition with stable gradients.

    Args:
      A: A real symmetric input matrix of shape (n, n).

    Returns:
      A tuple (output, residuals) where:
        - output: A tuple (evals, evecs) containing eigenvalues and eigenvectors.
        - residuals: A tuple ((evals, evecs), A) required for the backward pass.
    """
    evals, evecs = stable_eigh(A)
    return (evals, evecs), ((evals, evecs), A)


def stable_eigh_rev(
    res: tuple[tuple[Float[Array, "n"], Float[Array, "n n"]], Float[Array, "n n"]],
    g: tuple[Float[Array, "n"], Float[Array, "n n"]],
) -> tuple[Float[Array, "n n"]]:
    """Backward pass for symmetric eigendecomposition with stable gradients.

    Implements a numerically stable backward pass using the Lorentzian broadening
    approach to mitigate non-differentiability issues arising from (nearly)
    degenerate eigenvalues.

    Args:
      res: A tuple of residuals from the forward pass ((evals, evecs), A).
        - evals: Eigenvalues from the forward pass of shape (n,).
        - evecs: Eigenvectors from the forward pass of shape (n, n).
        - A: The original input matrix of shape (n, n).
      g: A tuple of gradients (grad_evals, grad_evecs) with respect to the
        outputs.

    Returns:
      A tuple containing the gradient with respect to the input matrix,
      symmetrized.

    References:
      Colburn, S., & Majumdar, A. (2021). Communications Physics, 4, 54.
      https://doi.org/10.1038/s42005-021-00568-6
      Jiao, Y., et al. (2022). Communications Physics, 5, 115.
      https://doi.org/10.1038/s42005-021-00568-6
    """
    # Used to return A but unused
    (evals, evecs), _ = res
    grad_evals, grad_evecs = g
    grad_evals_diag = jnp.diag(grad_evals)
    evecs_trans = evecs.T

    # Generate eigenvalue difference matrix
    eval_diff = evals.reshape((1, -1)) - evals.reshape((-1, 1))
    # Find elements where degen_tol condition was or wasn't was met
    mask_degen = (jnp.abs(eval_diff) < DEGENERACY_TOLERANCE).astype(jnp.int64)
    mask_non_degen = (jnp.abs(eval_diff) >= DEGENERACY_TOLERANCE).astype(jnp.int64)

    # Regular gap for non_degen terms => 1/(e_j - e_i)
    # Will get +infs turning to large numbers here if degeneracies are present.
    # This doesn't matter as they multiply by 0 in the forthcoming mask when calculating
    # the F-matrix
    regular_gap = jnp.nan_to_num(jnp.divide(1, eval_diff))

    # Lorentzian broadened gap for degen terms => (e_j - e_i)/((e_j - e_i)^2 + eps)
    broadened_gap = eval_diff / (eval_diff * eval_diff + BROADENING)

    # Calculate full F matrix. large numbers generated by NaNs from regular_gap are deleted here
    F = 0.5 * (jnp.multiply(mask_non_degen, regular_gap) + jnp.multiply(mask_degen, broadened_gap))

    # Set diagonals to 0
    F = F.at[jnp.diag_indices_from(F)].set(0)

    # Calculate the gradient
    grad = (
        jnp.linalg.inv(evecs_trans)
        @ (0.5 * grad_evals_diag + jnp.multiply(F, evecs_trans @ grad_evecs))
        @ evecs_trans
    )
    # Symmetrize
    return (grad + grad.T,)


stable_eigh.defvjp(stable_eigh_fwd, stable_eigh_rev)
stable_eigh_vec = jnp.vectorize(stable_eigh, signature="(m,m)->(n),(n,n)")


def stable_generalized_eigh(
    A: Float[Array, "n n"], B: Float[Array, "n n"]
) -> tuple[Float[Array, "n"], Float[Array, "n n"]]:
    r"""Solves the generalized symmetric eigenvalue problem AC = BCE.

    Computes the matrix of eigenvectors C and the diagonal matrix of
    eigenvalues E such that AC = BCE. Requires A and B to be real symmetric
    matrices, and B to be positive-definite (invertible).

    Args:
      A: A real symmetric matrix of shape (n, n).
      B: A real symmetric positive-definite matrix of shape (n, n).

    Returns:
      A tuple (evals, evecs) where:
        - evals: Generalized eigenvalues of shape (n,).
        - evecs: Matrix of shape (n, n) containing the generalized eigenvectors.
    """
    L = jnp.linalg.cholesky(B)
    L_inv = jnp.linalg.inv(L)
    C = L_inv @ A @ jnp.moveaxis(L_inv, -1, -2)
    eigenvalues, eigenvectors_transformed = stable_eigh_vec(C)
    eigenvectors_original = jnp.moveaxis(L_inv, -1, -2) @ eigenvectors_transformed
    return eigenvalues, eigenvectors_original


def stable_fock_solver(
    fock: Float[Array, "spin orbitals orbitals"], overlap: Float[Array, "orbitals orbitals"]
) -> tuple[Float[Array, "spin orbitals"], Float[Array, "spin orbitals orbitals"]]:
    """Computes eigenenergies and MO coefficients for spin-polarized Fock matrices.

    Args:
      fock: Spin-polarized Fock matrices of shape (spin, orbitals, orbitals).
      overlap: Overlap matrix of shape (orbitals, orbitals).

    Returns:
      A tuple (mo_energies, mo_coeffs) where:
        - mo_energies: Molecular orbital energies of shape (spin, orbitals).
        - mo_coeffs: Molecular orbital coefficients of shape
          (spin, orbitals, orbitals).
    """
    mo_energies_up, mo_coeffs_up = stable_generalized_eigh(fock[0], overlap)
    mo_energies_dn, mo_coeffs_dn = stable_generalized_eigh(fock[1], overlap)
    return jnp.stack((mo_energies_up, mo_energies_dn), axis=0), jnp.stack(
        (mo_coeffs_up, mo_coeffs_dn), axis=0
    )


if __name__ == "__main__":

    jax.config.update("jax_enable_x64", True)

    # 1. Test standard eigensolver stable_eigh
    print("Testing stable_eigh...")
    A = jnp.array([[2.0, 1.0], [1.0, 2.0]])
    evals, evecs = stable_eigh(A)
    print(f"Eigenvalues: {evals}")
    # Verify A * v = lambda * v
    assert jnp.allclose(A @ evecs, evecs @ jnp.diag(evals))

    # 2. Test generalized eigensolver stable_generalized_eigh
    print("\nTesting stable_generalized_eigh...")
    B = jnp.array([[1.0, 0.5], [0.5, 1.0]])  # Positive definite overlap
    evals_gen, evecs_gen = stable_generalized_eigh(A, B)
    print(f"General Eigenvalues: {evals_gen}")
    # Verify A * C = B * C * E
    assert jnp.allclose(A @ evecs_gen, B @ evecs_gen @ jnp.diag(evals_gen))

    # 3. Test Fock solver
    print("\nTesting stable_fock_solver...")
    fock = jnp.stack([A, A * 1.1], axis=0)  # Two spin channels
    mo_energies, mo_coeffs = stable_fock_solver(fock, B)
    print(f"MO Energies shape: {mo_energies.shape}") # Should be (2, 2)
    assert mo_energies.shape == (2, 2)

    # 4. Test gradients (including degenerate cases)
    print("\nTesting gradients...")

    def sum_eigenvalues(mat):
        ev, _ = stable_eigh(mat)
        return jnp.sum(ev)

    # Gradient at non-degenerate point
    grad_non_degen = jax.grad(sum_eigenvalues)(A)
    print(f"Gradient at non-degenerate matrix:\n{grad_non_degen}")
    assert not jnp.any(jnp.isnan(grad_non_degen))

    # Gradient at degenerate point (Identity matrix)
    print("Testing degenerate gradient (Identity matrix)...")

    A_degen = jnp.eye(2)
    grad_degen = jax.grad(sum_eigenvalues)(A_degen)
    print(f"Gradient at identity:\n{grad_degen}")
    assert not jnp.any(jnp.isnan(grad_degen))

    # Gradient at very degenerate point (Large matrix)
    print("Testing very degenerate gradient (Large matrix)...")
    key = jax.random.PRNGKey(0)
    Q, _ = jnp.linalg.qr(jax.random.normal(key, (10, 10)))
    A_large_degen = Q @ jnp.diag(jnp.array([1.0] * 5 + [2.0] * 5)) @ Q.T
    grad_large_degen = jax.grad(sum_eigenvalues)(A_large_degen)
    print(f"Gradient at large degenerate matrix:\n{grad_large_degen}")
    assert not jnp.any(jnp.isnan(grad_large_degen))

    print("\nAll quick tests passed!")
